Add prebuilt color theme variations and theme settings
MyCashflow/MyCashflow-Barebones-Theme pull request #14
Opened 2022-03-28 04:05 UTC by pulsejukka

2022-03-28 04:07 UTC, pulsejukka commented on theme.xml
> +			<Setting type="select" name="color_theme" label="color_theme" default="candy-red">
```suggestion
			<Setting type="select" name="color_theme" label="color_theme" default="jungle-green">
```

2022-03-28 08:35 UTC, teemku requested changes

2022-03-28 08:35 UTC, teemku commented on theme.xml
> +		<SettingGroup label="colors" description="colors_description">
Puuttuu käännökset `colors` ja `colors_description` avaimille.

2022-03-29 09:57 UTC, teemku approved these changes

2022-03-29 10:27 UTC, merged